### ISSUE TITLE
Uncaught TypeError: Cannot read property 'target' of undefined

### ISSUE THREAD

**Issue by edsko** [atom-haskell/ide-haskell#107]
@lierdakil With the latest master on `ide-haskell` and `ide-haskell-cabal` I get this as soon as I call `build`:

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: [ide-haskell](https://github.com/atom-haskell/ide-haskell) package, v0.7.2

### Stack Trace

Uncaught TypeError: Cannot read property 'target' of undefined

```
At /Users/e/wt/util/atom/ide-haskell/lib/plugin-manager.coffee:83

TypeError: Cannot read property 'target' of undefined
  at PluginManager.buildProject (/Users/e/wt/util/atom/ide-haskell/lib/plugin-manager.coffee:83:37)
  at PluginManager.buildProject (/Users/e/wt/util/atom/ide-haskell/lib/plugin-manager.coffee:1:1)
  at atom-workspace._this.disposables.add.atom.commands.add.ide-haskell:build (/Users/e/wt/util/atom/ide-haskell/lib/ide-haskell.coffee:331:28)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)

```

### Commands

```
     -0:08.8.0 command-palette:toggle (atom-pane.pane.active)
     -0:07.7.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:07.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:07.5.0 fuzzy-finder:toggle-file-finder (atom-pane.pane.active)
  2x -0:05.9.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:05.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:01.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.2.0 ide-haskell:build (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "spell-check",
      "cabal",
      "haskell-ghc-mod"
    ],
    "audioBeep": false
  },
  "ide-haskell": {
    "cabalPath": "/Users/e/opt/atom-bin/cabal",
    "onSaveLint": false,
    "onSaveCheck": false,
    "expressionTypeInterval": 3000,
    "useBuildBackend": "ide-haskell-cabal",
    "startupMessageIdeBackend": false
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-haskell, v0.5.1
ide-haskell, v0.7.2
ide-haskell-cabal, v0.0.0
language-diff, v0.3.1
language-haskell, v1.4.9

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
Ouch. Give me a minute.

**Comment by lierdakil** [comment]
Okay, should be fixed now. Sorry.

**Comment by edsko** [comment]
Ok, that seems to do it. That was quick :+1: :)
