### ISSUE TITLE
Uncaught TypeError: deprecationSite.getFileName is not a function

### ISSUE THREAD

**Issue by vishesh** [atom-haskell/ide-haskell#128]
Just upgraded to Atom 1.2, and get following error on startup.

**Atom Version**: 1.2.0
**System**: Ubuntu 15.10
**Thrown From**: [ide-haskell](https://github.com/atom-haskell/ide-haskell) package, v1.3.4

### Stack Trace

Uncaught TypeError: deprecationSite.getFileName is not a function

```
At /usr/share/atom/resources/app.asar/node_modules/grim/lib/grim.js:56

TypeError: deprecationSite.getFileName is not a function
    at Object.global.__grim__.deprecate (/usr/share/atom/resources/app.asar/node_modules/grim/lib/grim.js:56:36)
    at TextEditor.module.exports.TextEditor.onDidChangeScrollLeft (/usr/share/atom/resources/app.asar/src/text-editor.js:380:12)
    at new EditorControl (/home/vishesh/.atom/packages/ide-haskell/lib/editor-control.coffee:42:30)
    at PluginManager.addController (/home/vishesh/.atom/packages/ide-haskell/lib/plugin-manager.coffee:69:49)
    at PluginManager.controllerOnGrammar (/home/vishesh/.atom/packages/ide-haskell/lib/plugin-manager.coffee:88:8)
    at /home/vishesh/.atom/packages/ide-haskell/lib/plugin-manager.coffee:96:10
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at TextEditor.module.exports.TextEditor.handleGrammarChange (/usr/share/atom/resources/app.asar/src/text-editor.js:2705:27)
    at /usr/share/atom/resources/app.asar/src/text-editor.js:200:24
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atomic-emacs"
    ],
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  },
  "ide-haskell": {}
}
```

### Installed Packages

```coffee
# User
Repl, v0.5.0
autocomplete-haskell, v0.6.2
autocomplete-python, v0.10.3
haskell-ghc-mod, v1.1.3
ide-haskell, v1.3.4
ide-haskell-repl, v0.0.4
language-ocaml, v1.1.2
nuclide-ocaml, v0.0.32
vim-mode, v0.63.0

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
I will fix this shortly, but it's likely that your Atom install is somewhat broken. In particular, it doesn't seem that `grim` was installed with it, and gods know what else is missing.

**Comment by lierdakil** [comment]
1.3.5 shouldn't trigger this.

**Comment by vishesh** [comment]
Thanks! 1.3.5 fixed the issue.
