### ISSUE TITLE
Failed to activate the ide-haskell package: editorElement.onDidChangeScrollLeft is not a function

### ISSUE THREAD

**Issue by icyrockcom** [atom-haskell/ide-haskell#138]
[Enter steps to reproduce below:]

1. Open a Haskell file, so it is opened automatically when Atom starts
2. Close and open Atom

This seems to have started happening when I updated packages yesterday.

**Atom Version**: 1.0.19
**System**: "Fedora 22"
**Thrown From**: [ide-haskell](https://github.com/atom-haskell/ide-haskell) package, v1.3.9

### Stack Trace

Failed to activate the ide-haskell package

```
At editorElement.onDidChangeScrollLeft is not a function

TypeError: editorElement.onDidChangeScrollLeft is not a function
    at new EditorControl (/home/icyrock/.atom/packages/ide-haskell/lib/editor-control.coffee:40:36)
    at PluginManager.addController (/home/icyrock/.atom/packages/ide-haskell/lib/plugin-manager.coffee:69:49)
    at PluginManager.controllerOnGrammar (/home/icyrock/.atom/packages/ide-haskell/lib/plugin-manager.coffee:88:8)
    at /home/icyrock/.atom/packages/ide-haskell/lib/plugin-manager.coffee:97:8
    at Workspace.module.exports.Workspace.observeTextEditors (/usr/share/atom/resources/app.asar/src/workspace.js:276:9)
    at PluginManager.subscribeEditorController (/home/icyrock/.atom/packages/ide-haskell/lib/plugin-manager.coffee:94:37)
    at new PluginManager (/home/icyrock/.atom/packages/ide-haskell/lib/plugin-manager.coffee:21:6)
    at Object.module.exports.IdeHaskell.activate (/home/icyrock/.atom/packages/ide-haskell/lib/ide-haskell.coffee:147:26)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:245:19)
    at /usr/share/atom/resources/app.asar/src/package.js:917:28
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ],
    "disabledPackages": [
      "sensible-tab",
      "atom-paredit",
      "enhanced-tabs",
      "welcome"
    ],
    "autoHideMenuBar": true
  },
  "ide-haskell": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-haskell, v0.6.2
ctrl-last-tab, v0.3.0
haskell-ghc-mod, v1.6.6
ide-haskell, v1.3.9
ide-haskell-cabal, v1.0.0
language-elm, v1.3.2
language-haskell, v1.5.2
linter-hlint, v0.4.3
lisp-paredit, v0.5.2
tab-numbers, v0.3.0
vim-mode, v0.62.0

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
You probably need to update to Atom 1.2 or 1.3 at least. Sorry, don't have enough manpower to support older versions.

**Comment by icyrockcom** [comment]
Thanks @lierdakil! Works after updating to 1.5.2. It's more than reasonable not to support older versions, just me expecting that `dnf update atom` would update it... Thanks for the nice plugin and keep up the great work!
