### ISSUE TITLE
Uncaught TypeError: target.getModel is not a function

### ISSUE THREAD

**Issue by zmanian** [atom-haskell/ide-haskell#142]
[Enter steps to reproduce below:]

Error happens on lint, prettify etc

**Atom Version**: 1.5.3
**System**: Ubuntu 14.04.4
**Thrown From**: [ide-haskell](https://github.com/atom-haskell/ide-haskell) package, v1.4.2

### Stack Trace

Uncaught TypeError: target.getModel is not a function

```
At /home/zaki/.atom/packages/ide-haskell/lib/ide-haskell.coffee:159

TypeError: target.getModel is not a function
    at atom-text-editor.disposables.add.atom.commands.add.ide-haskell:close-tooltip (/home/zaki/.atom/packages/ide-haskell/lib/ide-haskell.coffee:159:11)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:260:29)
    at /opt/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:544:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:363:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/opt/atom/resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/opt/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:15.1.0 core:move-right (input.hidden-input)
  2x -0:14.7.0 core:move-down (input.hidden-input)
  7x -0:14.2.0 core:move-right (input.hidden-input)
     -0:13 core:move-left (input.hidden-input)
  3x -0:12.7.0 core:backspace (input.hidden-input)
     -0:10.8.0 core:move-right (input.hidden-input)
     -0:10.5.0 core:move-down (input.hidden-input)
  4x -0:10.2.0 core:move-left (input.hidden-input)
  2x -0:09.2.0 core:backspace (input.hidden-input)
  2x -0:08.2.0 core:move-down (input.hidden-input)
  2x -0:07.4.0 core:backspace (input.hidden-input)
     -0:06.3.0 core:save (input.hidden-input)
 12x -0:05.8.0 core:move-down (input.hidden-input)
 18x -0:04.7.0 core:move-up (input.hidden-input)
 14x -0:02.2.0 core:move-down (input.hidden-input)
     -0:00.9.0 ide-haskell:close-tooltip (input.hidden-input)
```

### Config

```json
{
  "core": {},
  "ide-haskell": {
    "stylishHaskellPath": "/home/zaki/.local/bin/stylish-haskell"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.24
atom-jade, v0.3.0
atom-ternjs, v0.13.2
auto-detect-indentation, v0.4.2
autocomplete-haskell, v0.6.2
color-picker, v2.1.1
haskell-ghc-mod, v1.7.0
hidpi, v0.11.0
ide-haskell, v1.4.2
ide-haskell-cabal, v1.0.0
jade-beautify, v0.1.4
language-haskell, v1.7.0
language-rust, v0.4.6
linter, v1.11.3
linter-coffeelint, v1.1.2
linter-jade, v0.3.2
linter-jshint, v2.0.2
linter-jsxhint, v0.1.2
linter-rust, v0.4.1
pigments, v0.24.1
symbols-tree-view, v0.11.0

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
Um. Your log seems to suggest you're pressing 'escape' (or possibly some other binding for `ide-haskell:close-tooltip` command), and for some reason there is no underlying model for editor element?

What element is in focus at the moment this error pops up? It seems it's not `atom-text-editor`, but rather a general `input` (probably from autocomplete-plus?), which, to my knowledge, shouldn't be bound to `ide-haskell:close-tooltip` command, unless you explicitly rebound it in your keymap. It's possible that this is some random conflict with another package.

**Comment by lierdakil** [comment]
Also if you updated ide-haskell recently, you might want to try to a) restart Atom and b) uninstall and reinstall ide-haskell, and then restart Atom. Maybe compilation got borked somewhere down the line.

**Comment by lierdakil** [comment]
Another possibility is that you have 'Use Shadow DOM' disabled in Atom settings. This is not supported, please enable it back.

**Comment by zmanian** [comment]
It was the Shadow DOM. Thanks!
