### ISSUE TITLE
Uncaught Error: Undefined screen line when clipping screen position

### ISSUE THREAD

**Issue by cblp** [atom-haskell/ide-haskell#164]
steps to reproduce: I don't know. Just closed some file...

**Atom Version**: 1.8.0
**System**: Ubuntu 16.04
**Thrown From**: [ide-haskell](https://github.com/atom-haskell/ide-haskell) package, v1.6.5

### Stack Trace

Uncaught Error: Undefined screen line when clipping screen position

```
At /usr/share/atom/resources/app.asar/src/display-buffer.js:890

Error: Undefined screen line when clipping screen position
    at DisplayBuffer.module.exports.DisplayBuffer.clipScreenPosition (/usr/share/atom/resources/app.asar/src/display-buffer.js:878:15)
    at DisplayBuffer.module.exports.DisplayBuffer.bufferPositionForScreenPosition (/usr/share/atom/resources/app.asar/src/display-buffer.js:830:20)
    at TextEditor.module.exports.TextEditor.bufferPositionForScreenPosition (/usr/share/atom/resources/app.asar/src/text-editor.js:1367:33)
    at module.exports.Utils.bufferPositionFromMouseEvent (/home/cblp/felix/home/.atom/packages/ide-haskell/lib/utils.coffee:14:12)
    at HTMLDivElement.<anonymous> (/home/cblp/felix/home/.atom/packages/ide-haskell/lib/editor-control.coffee:47:18)
    at HTMLDivElement.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
  5x -2:46.3.0 core:move-down (atom-text-editor.editor.is-focused)
     -2:45 core:select-all (atom-text-editor.editor.is-focused)
     -2:44.6.0 core:copy (atom-text-editor.editor.is-focused)
     -2:42 markdown-preview:toggle (atom-text-editor.editor.is-focused)
     -2:38.9.0 core:move-to-top (atom-text-editor.editor.is-focused)
  3x -2:38.4.0 core:move-down (atom-text-editor.editor.is-focused)
  4x -2:36.8.0 core:select-down (atom-text-editor.editor.is-focused)
     -2:36.1.0 snippets:previous-tab-stop (atom-text-editor.editor.is-focused)
     -2:36.1.0 markdown:outdent-list-item (atom-text-editor.editor.is-focused)
  3x -2:35.3.0 core:move-up (atom-text-editor.editor.is-focused)
     -2:34.1.0 core:move-down (atom-text-editor.editor.is-focused)
  7x -2:33.8.0 core:select-down (atom-text-editor.editor.is-focused)
     -2:31.3.0 core:select-all (atom-text-editor.editor.is-focused)
     -2:30.7.0 core:copy (atom-text-editor.editor.is-focused)
     -0:05.7.0 markdown-preview:toggle (atom-text-editor.editor.is-focused)
     -0:04.7.0 core:close (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-gfm"
    ],
    "openEmptyEditorOnStart": false
  },
  "ide-haskell": {
    "onCursorMove": "Hide Tooltip",
    "onSavePrettify": true,
    "startupMessageIdeBackend": false,
    "stylishHaskellPath": "/home/cblp/.local/bin/stylish-haskell"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-haskell, v0.6.5
haskell-ghc-mod, v1.14.5
highlight-selected, v0.11.2
ide-haskell, v1.6.5
ide-haskell-stack, v0.0.3
language-cpp14, v0.6.1
language-docker, v1.1.6
language-haskell, v1.7.16
language-markdown, v0.14.0
linter, v1.11.4
linter-pylint, v1.2.0

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
I have no idea on how to reproduce this. Just updated to 1.8.0 and normal usage doesn't seem to be affected.

**Comment by lierdakil** [comment]
Okay, so this might have been fixed. Or not. I have no idea. Conditions for manifestation seem to be extremely precise and rare at that. So I'm choosing to close this. If anyone runs into this problem again, feel free to let me know here or in new issue.
