### ISSUE TITLE
Uncaught Error: Cannot find module 'atom-space-pen-views

### ISSUE THREAD

**Issue by garethrowlands** [atom-haskell/ide-haskell#171]
I get this if I click on 'Builder: not set'. I don't know why Builder is not set.

**Comment by fstiffo** [comment]
Me too.

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.9.9
**System**: Unknown Windows Version
**Thrown From**: [ide-haskell](https://github.com/atom-haskell/ide-haskell) package, v1.7.1


### Stack Trace

Uncaught Error: Cannot find module 'atom-space-pen-views'

```
At module.js:341

Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:339:15)
    at Function.Module._resolveFilename (C:\Users\Francesco\AppData\Local\atom\app-1.9.9\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (C:\Users\Francesco\AppData\Local\atom\app-1.9.9\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/Francesco/.atom/packages/ide-haskell/lib/output-panel/views/param-select-view.coffee:1:20)
    at Object.<anonymous> (file:///C:/Users/Francesco/.atom/packages/ide-haskell/lib/output-panel/views/param-select-view.coffee:1:1)
    at Module._compile (C:\Users\Francesco\AppData\Local\atom\app-1.9.9\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\Francesco\AppData\Local\atom\app-1.9.9\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\Francesco\AppData\Local\atom\app-1.9.9\resources\app.asar\src\native-compile-cache.js:50:27)
    at _this.changeParamFs.(anonymous function).(anonymous function).change (file:///C:/Users/Francesco/.atom/packages/ide-haskell/lib/plugin-manager.coffee:125:29)
    at HTMLElement.disp.add._this.outputView.addPanelControl.events.click (file:///C:/Users/Francesco/.atom/packages/ide-haskell/lib/plugin-manager.coffee:137:23)
    at HTMLElement.jQuery.event.dispatch (C:\Users\Francesco\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at HTMLElement.elemData.handle (C:\Users\Francesco\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)
```

### Commands

```
     -8:31.5.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -8:18.8.0 core:save (atom-text-editor.editor.is-focused)
     -7:37.4.0 haskell-ghc-mod:check-file (atom-text-editor.editor.is-focused)
     -7:33.3.0 haskell-ghc-mod:lint-file (atom-text-editor.editor.is-focused)
     -7:20.5.0 ide-haskell-cabal:build (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "ide-haskell": {}
}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.16.4 (inactive)
atom-elixir, v0.2.1 (active)
atom-yeoman, v0.3.15 (active)
autocomplete-haskell, v0.6.6 (active)
build, v0.65.0 (active)
build-elixir, v0.6.0 (active)
busy, v0.6.0 (active)
haskell-ghc-mod, v1.17.2 (active)
ide-haskell, v1.7.1 (active)
ide-haskell-cabal, v1.6.2 (active)
ide-haskell-repl, v0.1.1 (active)
ionide-fake, v1.2.2 (active)
ionide-fsharp, v1.9.1 (active)
ionide-fsi, v2.1.3 (active)
ionide-installer, v1.3.0 (active)
ionide-paket, v2.2.6 (active)
ionide-webview, v1.0.3 (active)
ionide-yeoman, v1.0.2 (active)
language-elixir, v0.16.0 (active)
language-haskell, v1.9.7 (active)
linter, v1.11.16 (active)
open-terminal-here, v2.1.4 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (active)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.1 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.1 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
Ouch. Sorry, I messed up. v1.7.2 should be fine.

**Comment by lierdakil** [comment]
For reference, 'Builder: not set' is the default for new projects (after 1.7 update, all projects are treated as "new", old project-specific settings are "forgotten"). Selection dialog should pop up automatically when needed, and selection *will* be saved between restarts on per-project basis. Problem is I messed up dependencies, so it never worked. Sorry again.

**Comment by fstiffo** [comment]
Thanks Nikolay
