### ISSUE TITLE
Uncaught TypeError: resItem.destroy is not a function

### ISSUE THREAD

**Issue by bobbyrauchenberg** [atom-haskell/ide-haskell#197]
Hi 
I'm just using the Haskell-IDE with Haskell-IDE-Repl and intermittently when i press any key i get the error shown below:

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [ide-haskell](https://github.com/atom-haskell/ide-haskell) package 1.9.5

### Stack Trace

Uncaught TypeError: resItem.destroy is not a function

```
At /Users/bra14/.atom/packages/ide-haskell/lib/editor-control.coffee:113

TypeError: resItem.destroy is not a function
    at /packages/ide-haskell/lib/editor-control.coffee:113:17
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at DisplayMarker.module.exports.DisplayMarker.notifyObservers (/app.asar/node_modules/text-buffer/lib/display-marker.js:248:27)
    at /app.asar/node_modules/text-buffer/lib/display-marker.js:53:26
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Marker.module.exports.Marker.emitChangeEvent (/app.asar/node_modules/text-buffer/lib/marker.js:421:20)
    at /app.asar/node_modules/text-buffer/lib/marker-layer.js:312:25
    at Set.forEach (native)
    at MarkerLayer.module.exports.MarkerLayer.emitChangeEvents (/app.asar/node_modules/text-buffer/lib/marker-layer.js:309:39)
    at TextBuffer.module.exports.TextBuffer.emitMarkerChangeEvents (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1334:34)
    at TextBuffer.module.exports.TextBuffer.transact (/app.asar/node_modules/text-buffer/lib/text-buffer.js:843:12)
    at TextEditor.module.exports.TextEditor.transact (/app.asar/src/text-editor.js:1551:26)
    at /app.asar/src/text-editor.js:1128:24
    at TextEditor.module.exports.TextEditor.mergeSelections (/app.asar/src/text-editor.js:2524:43)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/app.asar/src/text-editor.js:2490:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/app.asar/src/text-editor.js:1126:19)
    at TextEditor.module.exports.TextEditor.insertText (/app.asar/src/text-editor.js:1092:19)
    at /app.asar/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
    at TextEditorComponent.module.exports.TextEditorComponent.onTextInput (/app.asar/src/text-editor-component.js:478:26)
    at /app.asar/src/text-editor-component.js:3:59)
```

### Commands

```
     -4:45.8.0 core:backspace (input.hidden-input)
     -4:40.3.0 ide-haskell:close-tooltip (input.hidden-input)
     -4:40.3.0 autocomplete-haskell:conceal-hint-panel (input.hidden-input)
     -4:40.3.0 editor:consolidate-selections (input.hidden-input)
     -4:40.3.0 core:cancel (input.hidden-input)
     -4:39.6.0 ide-haskell:close-tooltip (input.hidden-input)
     -4:39.6.0 autocomplete-haskell:conceal-hint-panel (input.hidden-input)
     -4:39.6.0 editor:consolidate-selections (input.hidden-input)
     -4:39.6.0 core:cancel (input.hidden-input)
     -4:38.3.0 core:save (input.hidden-input)
     -4:33.6.0 ide-haskell-repl:ghci-reload (input.hidden-input)
  2x -2:33.7.0 core:backspace (input.hidden-input)
  5x -2:31 editor:move-to-end-of-word (input.hidden-input)
  4x -2:28.1.0 editor:move-to-beginning-of-word (input.hidden-input)
     -2:26.8.0 editor:select-to-end-of-line (input.hidden-input)
     -2:24.8.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-haskell 0.7.2 
haskell-ghc-mod 1.19.7 
ide-haskell 1.9.5 
ide-haskell-cabal 1.8.1 
ide-haskell-repl 0.5.2 
language-haskell 1.12.1 
term3 0.22.1 
```

**Comment by lierdakil** [comment]
Should be fixed in v1.9.6. Thanks for reporting!
