### ISSUE TITLE
Uncaught TypeError: Cannot read property 'emit' of null

### ISSUE THREAD

**Issue by bobbyrauchenberg** [atom-haskell/ide-haskell#198]
Sorry, i raised an issue earlier (https://github.com/atom-haskell/ide-haskell/issues/197) which you said was fixed in 1.9.6, so i upgraded and now get this. Apologies if I've done something stupid along the way :)

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [ide-haskell](https://github.com/atom-haskell/ide-haskell) package 1.9.6

### Stack Trace

Uncaught TypeError: Cannot read property 'emit' of null

```
At /Users/bra14/.atom/packages/ide-haskell/lib/results-db.coffee:56

TypeError: Cannot read property 'emit' of null
    at ResultsDB.module.exports.ResultsDB.setResults (/packages/ide-haskell/lib/results-db.coffee:56:26)
    at UPIInstance.setMessages (/packages/ide-haskell/lib/upi.coffee:78:33)
    at IdeHaskellReplView.module.exports.IdeHaskellReplView.setError (/packages/ide-haskell-repl/lib/ide-haskell-repl-view.coffee:217:12)
    at ghci.GHCI.onError (/packages/ide-haskell-repl/lib/ide-haskell-repl-view.coffee:155:10)
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /packages/ide-haskell-repl/lib/ghci.coffee:85:20
    at /packages/ide-haskell-repl/lib/ghci.coffee:59:13)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20)
```

### Commands

```
  4x -1:47.4.0 core:backspace (input.hidden-input)
     -1:46.3.0 core:save (input.hidden-input)
  3x -1:46 core:backspace (input.hidden-input)
     -1:45 core:save (input.hidden-input)
  2x -1:42.9.0 core:undo (input.hidden-input)
     -1:40.9.0 core:save (input.hidden-input)
  4x -1:01.3.0 core:move-down (input.hidden-input)
  4x -1:00.1.0 core:move-up (input.hidden-input)
     -0:30.2.0 core:backspace (input.hidden-input)
     -0:28.8.0 core:save (input.hidden-input)
  3x -0:17.4.0 core:move-right (input.hidden-input)
     -0:16 core:save (input.hidden-input)
     -0:15.3.0 core:move-right (input.hidden-input)
     -0:14.8.0 core:backspace (input.hidden-input)
     -0:14.6.0 core:save (input.hidden-input)
     -0:10.7.0 ide-haskell-repl:ghci-reload (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-haskell 0.7.2 
haskell-ghc-mod 1.19.7 
ide-haskell 1.9.6 
ide-haskell-cabal 1.8.1 
ide-haskell-repl 0.5.2 
language-haskell 1.12.1 
term3 0.22.1 
```

**Comment by lierdakil** [comment]
Uh... did you restart Atom after updating? It usually wants you to...

**Comment by lierdakil** [comment]
I'm pretty sure this can only happen if ide-haskell goes away (disabled, removed or updated) with repl open...

**Comment by bobbyrauchenberg** [comment]
Yeah i restarted. I've just been using ghci through Term3 today (i.e. no repl) and have not seen the issue

**Comment by lierdakil** [comment]
So... you closed the issue. Did it "fix itself" or do you have other reasons?
