### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getPath' of undefined

### ISSUE THREAD

**Issue by vitormmatos** [atom-haskell/ide-haskell#210]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.13
**Thrown From**: [ide-haskell](https://github.com/atom-haskell/ide-haskell) package 2.0.1

### Stack Trace

Uncaught TypeError: Cannot read property 'getPath' of undefined

```
At /Users/vitormatos/.atom/packages/ide-haskell/lib/output-panel/index.js:148

TypeError: Cannot read property 'getPath' of undefined
    at OutputPanel.updateItems (/packages/ide-haskell/lib/output-panel/index.js:148:66)
    at OutputPanel.disposables.add.atom.workspace.onDidChangeActivePaneItem (/packages/ide-haskell/lib/output-panel/index.js:44:22)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Workspace.didChangeActivePaneItemOnPaneContainer (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:493:28)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem (/Applications/Atom.app/Contents/Resources/app/src/workspace-center.js:17:20)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PaneContainer.didChangeActiveItemOnPane (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:284:26)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:339:22)
    at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:492:27)
    at Immediate.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:702:30)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

### Commands

```
     -3:07.1.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
     -2:39.3.0 core:confirm (input.hidden-input)
     -2:30.3.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-mac-classic.theme-native-ui)
     -1:30.9.0 core:confirm (input.hidden-input)
     -0:45.4.0 ide-haskell:prettify-file (atom-pane.pane)
  2x -0:25.6.0 autocomplete-haskell:toggle-completion-hint (ul.list-inline.tab-bar.inset-panel)
  2x -0:21.3.0 ide-haskell:toggle-output (ul.list-inline.tab-bar.inset-panel)
```

### Non-Core Packages

```
apple-wwdc-2016-syntax 0.6.0 
astromac-ui 0.1.0 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
autocomplete-haskell 1.0.0 
file-icons 2.1.10 
ide-haskell 2.0.1 
language-common-lisp 0.9.5 
language-haskell 1.12.1 
language-r 0.4.1 
mac-classic 0.5.0 
mac-os-ui 0.3.0 
native-ui 0.21.0 
platformio-ide-terminal 2.5.5 
script 3.15.0 
slack-ui 0.8.0 
```

**Comment by lierdakil** [comment]
Thanks for reporting! Should be fixed in v2.0.2
