### ISSUE TITLE
Error: ide-haskell-cabal is not defined while trying to get ide-haskell-cabal.builder

### ISSUE THREAD

**Issue by AiDinho** [atom-haskell/ide-haskell#214]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [ide-haskell](https://github.com/atom-haskell/ide-haskell) package 2.1.1

### Stack Trace

Error: ide-haskell-cabal is not defined while trying to get ide-haskell-cabal.builder

```
At Error: ide-haskell-cabal is not defined while trying to get ide-haskell-cabal.builder

Error: ide-haskell-cabal is not defined while trying to get ide-haskell-cabal.builder
    at /packages/ide-haskell/lib/config-params/param-store.js:104:23)
    at Generator.next (<anonymous>)
    at /packages/ide-haskell/lib/config-params/param-store.js:7:71
    at __awaiter (/packages/ide-haskell/lib/config-params/param-store.js:3:12)
    at ConfigParamStore.getParamConfig (/packages/ide-haskell/lib/config-params/param-store.js:94:16)
    at /packages/ide-haskell/lib/config-params/param-store.js:76:44)
    at Generator.next (<anonymous>)
    at /packages/ide-haskell/lib/config-params/param-store.js:7:71
    at __awaiter (/packages/ide-haskell/lib/config-params/param-store.js:3:12)
    at ConfigParamStore.getValue (/packages/ide-haskell/lib/config-params/param-store.js:75:16)
    at /packages/ide-haskell/lib/config-params/index.js:40:31)
    at Generator.next (<anonymous>)
    at /packages/ide-haskell/lib/config-params/index.js:7:71
    at __awaiter (/packages/ide-haskell/lib/config-params/index.js:3:12)
    at ConfigParamManager.get (/packages/ide-haskell/lib/config-params/index.js:39:16)
    at /packages/ide-haskell/lib/upi-3/instance.js:59:57)
    at Generator.next (<anonymous>)
    at /packages/ide-haskell/lib/upi-3/instance.js:7:71
    at __awaiter (/packages/ide-haskell/lib/upi-3/instance.js:3:12)
    at Object.getOthersConfigParam (/packages/ide-haskell/lib/upi-3/instance.js:58:20)
    at /packages/ide-haskell-repl/lib/ide-haskell-repl-base.js:176:48)
    at Generator.next (<anonymous>)
    at fulfilled (/packages/ide-haskell-repl/lib/ide-haskell-repl-base.js:4:58)
```

### Commands

```
  2x -8:28.3.0 core:backspace (input.hidden-input)
     -2:49 ide-haskell-repl:toggle (input.hidden-input)
  4x -0:51.7.0 core:backspace (input.hidden-input)
     -0:50.2.0 core:paste (input.hidden-input)
     -0:14.6.0 ide-haskell-repl:toggle (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-haskell 1.0.1 
autocomplete-java 1.2.7 
haskell-ghc-mod 2.1.0 
ide-haskell 2.1.1 
ide-haskell-cabal 2.0.2 
ide-haskell-repl 0.7.3 
language-erlang 3.2.0 
language-haskell 1.14.1 
```

**Comment by lierdakil** [comment]
I was eventually able to reproduce it, but it happens, apparently, when ide-haskell was disabled after activation, and *then* ide-haskell-repl is started. Might also happen if ide-haskell is updated. This is a very particular set of circumstances, and it doesn't break anything, so I'm inclined to leave this as-is.

Let me know if it happened under different circumstances. And sorry I didn't get back to you sooner.
