### ISSUE TITLE
Uncaught TypeError: Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by athanclark** [atom-haskell/ide-haskell#51]
Hi folks, I just recently installed the latest version of ghc-mod. It works fine, I've tested it a few times. Just wondering what could cause this issue.

**Atom Version**: 0.198.0
**System**: linux 3.19.0-15-generic
**Thrown From**: [ide-haskell](https://github.com/chaika2013/ide-haskell) package, v0.3.6

### Stack Trace

Uncaught TypeError: Cannot read property 'on' of undefined

```
At /home/athan/.atom/packages/ide-haskell/lib/util-ghc-mod.coffee:26

TypeError: Cannot read property 'on' of undefined
  at run (/home/athan/.atom/packages/ide-haskell/lib/util-ghc-mod.coffee:26:15)
  at Object.check [as func] (/home/athan/.atom/packages/ide-haskell/lib/util-ghc-mod.coffee:37:3)
  at PendingBackend.processPendingTask (/home/athan/.atom/packages/ide-haskell/lib/pending-backend.coffee:49:26)
  at PendingBackend.start (/home/athan/.atom/packages/ide-haskell/lib/pending-backend.coffee:24:6)
  at PluginManager.checkOrLintFile (/home/athan/.atom/packages/ide-haskell/lib/plugin-manager.coffee:73:31)
  at PluginManager.checkFile (/home/athan/.atom/packages/ide-haskell/lib/plugin-manager.coffee:40:6)
  at atom-workspace._disposables.add.atom.commands.add.ide-haskell:check-file (/home/athan/.atom/packages/ide-haskell/lib/ide-haskell.coffee:50:22)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:238:29)
  at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:153:19)
  at EventEmitter.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:71:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
  2x -2:28.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 10x -1:04.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -0:58.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 10x -0:53.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:01.0 ide-haskell:check-file (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "ide-haskell": {
    "ghcModPath": "/home/athan/lib/ghc-mod/.cabal-sandbox/bin"
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v1.7.0
ide-haskell, v0.3.6
language-haskell, v1.0.0
linter, v0.12.2
linter-hlint, v0.3.4

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
Probably breaking API change in 0.198.0. I'll see what I can do.

**Comment by lierdakil** [comment]
Apparently not. Just updated to 0.198.0 and it works as expected for me.

**Comment by lierdakil** [comment]
I have little idea why this actually happens. Could you describe in more detail, when do you experience this error?

**Comment by lierdakil** [comment]
Closing, since most of code producing this issue was scrapped and there is no activity.
