### ISSUE TITLE
Closing a file throws an error

### ISSUE THREAD

**Issue by kRITZCREEK** [atom-haskell/ide-haskell#56]
tested with both 0.5.0 and 0.5.1

```
TypeError: Cannot read property 'dispose' of null
  at EditorControl.hideExpressionType (/home/creek/.atom/packages/ide-haskell/lib/editor-control.coffee:154:20)
  at EditorControl.clearExprTypeTimeout (/home/creek/.atom/packages/ide-haskell/lib/editor-control.coffee:80:6)
  at EditorControl.deactivate (/home/creek/.atom/packages/ide-haskell/lib/editor-control.coffee:69:6)
  at PluginManager.removeController (/home/creek/.atom/packages/ide-haskell/lib/plugin-manager.coffee:88:31)
  at /home/creek/.atom/packages/ide-haskell/lib/plugin-manager.coffee:85:10
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextEditor.module.exports.TextEditor.destroyed (/usr/share/atom/resources/app.asar/src/text-editor.js:265:27)
  at TextEditor.module.exports.Model.destroy (/usr/share/atom/resources/app.asar/node_modules/theorist/lib/model.js:218:14)
  at Pane.module.exports.Pane.destroyItem (/usr/share/atom/resources/app.asar/src/pane.js:444:18)
  at Pane.module.exports.Pane.destroyActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:419:12)
  at Workspace.module.exports.Workspace.destroyActivePaneItem (/usr/share/atom/resources/app.asar/src/workspace.js:593:35)
  at Workspace.module.exports.Workspace.destroyActivePaneItemOrEmptyPane (/usr/share/atom/resources/app.asar/src/workspace.js:632:21)
  at atom-workspace.atom.commands.add.core:close (/usr/share/atom/resources/app.asar/src/workspace-element.js:311:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:238:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:178:20)
```

**Comment by lierdakil** [comment]
Thanks for report. Sorry about that, not sure how it slipped into release.

**Comment by kRITZCREEK** [comment]
No worries! Thank you a lot for doing this. I enjoy the more "lightweight" editing experience in Atom thanks to your haskell packages :+1:

I'll try to improve my CoffeScript-Fu and contribute a bit
