### ISSUE TITLE
Failed to activate the ide-haskell package At undefined is not a function

### ISSUE THREAD

**Issue by burabure** [atom-haskell/ide-haskell#61]
ghc-mod and modi installed and both in path and plugin settings

**Atom Version**: 0.190.0
**System**: linux 3.13.0-45-generic
**Thrown From**: [ide-haskell](https://github.com/atom-haskell/ide-haskell) package, v0.5.5

### Stack Trace

Failed to activate the ide-haskell package

```
At undefined is not a function

TypeError: undefined is not a function
    at new EditorControl (/home/burabure/.atom/packages/ide-haskell/lib/editor-control.coffee:22:33)
    at PluginManager.addController (/home/burabure/.atom/packages/ide-haskell/lib/plugin-manager.coffee:167:38)
    at PluginManager.controllerOnGrammar (/home/burabure/.atom/packages/ide-haskell/lib/plugin-manager.coffee:186:21)
    at /home/burabure/.atom/packages/ide-haskell/lib/plugin-manager.coffee:198:24
    at Workspace.module.exports.Workspace.observeTextEditors (/usr/share/atom/resources/app/src/workspace.js:266:9)
    at PluginManager.subscribeEditorController (/home/burabure/.atom/packages/ide-haskell/lib/plugin-manager.coffee:193:50)
    at new PluginManager (/home/burabure/.atom/packages/ide-haskell/lib/plugin-manager.coffee:25:12)
    at Object.module.exports.IdeHaskell.initIdeHaskell (/home/burabure/.atom/packages/ide-haskell/lib/ide-haskell.coffee:233:28)
    at Object.module.exports.IdeHaskell.activate (/home/burabure/.atom/packages/ide-haskell/lib/ide-haskell.coffee:199:12)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:225:19)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "base16-edark-syntax"
    ],
    "disabledPackages": [
      "linter-jshint",
      "linter-htmlhint",
      "ide-flow",
      "linter-flow",
      "Tern",
      "linter-hlint"
    ]
  },
  "ide-haskell": {}
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.12.1
atom-color-highlight, v3.0.9
autocomplete-haskell, v0.4.2
autocomplete-paths, v1.0.2
autocomplete-plus, v2.17.3
base16-edark-syntax, v0.0.0
emmet, v2.3.10
file-icons, v1.5.5
haskell-ghc-mod, v0.6.2
ide-haskell, v0.5.5
jsonlint, v1.1.2
linter, v0.12.6
linter-coffeelint, v0.2.4
linter-eslint, v0.5.8
project-palette-finder, v2.4.17
script, v2.23.0
symbols-tree-view, v0.9.3
wakatime, v4.0.9

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
Thank you for taking time to report this.
First, please try installing `language-haskell` package, which should give you syntax highlighting and is required for haskell source detection by ide-haskell.

Also, please consider updating your Atom to latest version (v0.204.0) since, this might be a bug in Atom.

If this error persists, consider opening a new bug, since stacktrace doesn't make sense to me, and I hope newer version will produce something more meaningful.

**Comment by burabure** [comment]
yep, has to update Atom. thanks!

**Comment by lierdakil** [comment]
Glad to hear this is resolved. Thanks for the update.

**Comment by WiWa** [comment]
Issue occurred despite a stabl Atom release + language-haskell

\> atom --version
`1.0.19`

\> apm list
...
├── ide-haskell@1.3.5
├── language-haskell@1.5.1
...

Stack Trace:
`
TypeError: editorElement.onDidChangeScrollLeft is not a function
    at new EditorControl (/home/win/.atom/packages/ide-haskell/lib/editor-control.coffee:40:36)
    at PluginManager.addController (/home/win/.atom/packages/ide-haskell/lib/plugin-manager.coffee:69:49)
    at PluginManager.controllerOnGrammar (/home/win/.atom/packages/ide-haskell/lib/plugin-manager.coffee:88:8)
    at /home/win/.atom/packages/ide-haskell/lib/plugin-manager.coffee:97:8
    at Workspace.module.exports.Workspace.observeTextEditors (/usr/share/atom/resources/app.asar/src/workspace.js:276:9)
    at PluginManager.subscribeEditorController (/home/win/.atom/packages/ide-haskell/lib/plugin-manager.coffee:94:37)
    at new PluginManager (/home/win/.atom/packages/ide-haskell/lib/plugin-manager.coffee:21:6)
    at Object.module.exports.IdeHaskell.activate (/home/win/.atom/packages/ide-haskell/lib/ide-haskell.coffee:145:26)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:245:19)
    at /usr/share/atom/resources/app.asar/src/package.js:917:28
`

**Comment by lierdakil** [comment]
@WiWa, update to 1.2 (which is current stable, 1.0 is outdated). Devs broke extended API. This happens. There is no way to support multiple Atom versions.
