### ISSUE TITLE
Uncaught TypeError: Cannot read property 'setBufferPosition' of undefined

### ISSUE THREAD

**Issue by Qinka** [atom-haskell/ide-haskell#65]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.207.0
**System**: Unknown Windows Version
**Thrown From**: [ide-haskell](https://github.com/atom-haskell/ide-haskell) package, v0.5.9

### Stack Trace

Uncaught TypeError: Cannot read property 'setBufferPosition' of undefined

```
At C:\Users\Qinka\.atom\packages\ide-haskell\lib\plugin-manager.coffee:74

TypeError: Cannot read property 'setBufferPosition' of undefined
  at util.prettify.onComplete (C:\Users\Qinka\.atom\packages\ide-haskell\lib\plugin-manager.coffee:74:31)
  at BufferedProcess.exit (C:\Users\Qinka\.atom\packages\ide-haskell\lib\util-stylish-haskell.coffee:17:14)
  at triggerExitCallback (C:\Users\Qinka\AppData\Local\atom\app-0.207.0\resources\app.asar\src\buffered-process.js:213:47)
  at C:\Users\Qinka\AppData\Local\atom\app-0.207.0\resources\app.asar\src\buffered-process.js:220:18
  at Socket.<anonymous> (C:\Users\Qinka\AppData\Local\atom\app-0.207.0\resources\app.asar\src\buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
     -0:31.8.0 core:save (ul.list-inline.tab-bar.inset-panel)
  4x -0:28.1.0 atom-save-all:saveAll (atom-text-editor.editor.is-focused)
     -0:24.6.0 ide-haskell:prettify-file (atom-text-editor.editor.is-focused)
     -0:24.6.0 ide-haskell:check-file (atom-text-editor.editor.is-focused)
     -0:24.6.0 ide-haskell:lint-file (atom-text-editor.editor.is-focused)
  5x -0:18.4.0 core:undo (atom-text-editor.editor.is-focused)
     -0:02.0 ide-haskell:prettify-file (atom-text-editor.editor.is-focused)
     -0:01.9.0 ide-haskell:check-file (atom-text-editor.editor.is-focused)
     -0:01.9.0 ide-haskell:lint-file (atom-text-editor.editor.is-focused)
     -0:01.9.0 ide-haskell:prettify-file (atom-text-editor.editor)
     -0:01.9.0 ide-haskell:check-file (atom-text-editor.editor)
     -0:01.9.0 ide-haskell:lint-file (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "destroyEmptyPanes": false
  },
  "ide-haskell": {
    "closeTooltipsOnCursorMove": true,
    "onMouseHoverShow": "Info",
    "onSavePrettify": true,
    "useBackend": "haskell-ghc-mod"
  }
}
```

### Installed Packages

```coffee
# User
atom-save-all, v0.2.0
autocomplete-haskell, v0.4.3
haskell-ghc-mod, v0.7.1
haskell-grammar, v0.3.0
haskell-pointfree, v0.1.2
ide-haskell, v0.5.9
language-haskell, v1.0.0
linter-hlint, v0.3.6
save-commands, v0.6.2

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
Thank you for reporting. This should be fixed in v0.5.10. Feel free to reopen if the problem persists in some form.
