### ISSUE TITLE
Uncaught TypeError: Cannot read property 'stdin' of undefined

### ISSUE THREAD

**Issue by BlakePai** [atom-haskell/ide-haskell#96]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.4
**Thrown From**: [ide-haskell](https://github.com/atom-haskell/ide-haskell) package, v0.7.1

### Stack Trace

Uncaught TypeError: Cannot read property 'stdin' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:801

TypeError: Cannot read property 'stdin' of undefined
  at Object.prettify (/Volumes/Data HD/BlakePai/.atom/packages/ide-haskell/lib/util-stylish-haskell.coffee:26:15)
  at PluginManager.prettifyFile (/Volumes/Data HD/BlakePai/.atom/packages/ide-haskell/lib/plugin-manager.coffee:84:10)
  at atom-text-editor.disposables.add.atom.commands.add.ide-haskell:prettify-file (/Volumes/Data HD/BlakePai/.atom/packages/ide-haskell/lib/ide-haskell.coffee:233:26)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:156:19)
  at /Volumes/Data HD/BlakePai/.atom/packages/ide-haskell/lib/editor-control.coffee:38:23
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1000:20)
  at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:992:19)
  at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:579:26)
  at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:539:18)
  at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:522:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:609:35)
  at atom-workspace.atom.commands.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace-element.js:293:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
  2x -3:02.2.0 core:save (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -1:50.1.0 core:close (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:12.8.0 ide-haskell:check-file (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:41.5.0 vim-mode:move-left (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:41.1.0 vim-mode:move-right (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:39.8.0 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  4x -0:39.3.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:38.4.0 core:move-down (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  4x -0:38.1.0 core:move-right (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  4x -0:37.3.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  3x -0:36.4.0 core:move-down (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:35.4.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:34.2.0 core:save (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:34.2.0 ide-haskell:prettify-file (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:01.0 core:save (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:01.0 ide-haskell:prettify-file (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
```

### Config

```json
{
  "core": {},
  "ide-haskell": {
    "onSavePrettify": true
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-haskell, v0.4.5
autocomplete-python, v0.5.3
haskell-ghc-mod, v0.8.10
haskell-pointfree, v0.1.2
ide-haskell, v0.7.1
language-haskell, v1.3.1
travis-ci-status, v0.16.0
vim-mode, v0.58.0

# Dev
No dev packages
```

**Comment by ben-burlingham** [comment]
I had this problem because my configuration was pointing to the `bin` where `stylish-haskell` is: `~/Library/Haskell/bin` (wrong).

When I updated the config to point to the binary itself, it worked fine: `~/Library/Haskell/bin/stylish-haskell` (correct).
